import { Poppins } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/global/sidebar/app-sidebar";
import ReduxProvider from "@/components/providers/ReduxProviders";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ReduxProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-[100%]">
              {/* <SidebarTrigger /> */}
              {children}
            </main>
          </SidebarProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
